[package]
name = "utilities"
version = "0.1.0"
authors = ["Kath Nicholls <nichollskc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.8.2"
log = "0.4"
